patch/0001-xfusion-vLLM-support-draft-model.patch
patch/0002-xfusion-vLLM-optimizing-speculative-decoding-open-source.patch
patch/0003-xfusion-vLLM-optimizing-speculative-decoding.patch
patch/0004-xfusion-vLLM-fix-nixl-connector-num-blocks-check.patch
patch/0005-xfusion-vLLM-support-sparsekv.patch
patch/0006-xfusion-vLLM-fix-GLM4-MoE-FP8-loading-with-MTP.patch
patch/0007-xfusion-vLLM-Handle-trust_remote_code-for-transformers-backend.patch
patch/0008-xfusion-vLLM-Replace-urllibs-urlparse-with-urllib3s-parse_url.patch
