patch/0001-xfusion-vLLM-ascend-soft-fp8-fp4-quantization-suppor.patch
patch/0002-xfusion-vLLM-ascend-bugfix-the-out-of-memory-caused-.patch
patch/0003-xfusion-vLLM-ascend-aclgraph-adaptation-for-fp8-and-.patch
patch/0004-xfusion-vLLM-ascend-Ears-a-efficient-adaptive-reject.patch
patch/0005-xfusion-vLLM-ascend-Qwen3-vl-xlite-adaptation.patch
patch/0006-xfusion-vLLM-ascend-fix-Suffix-Decoding.patch
patch/0007-xfusion-vLLM-ascend-The-ears-feature-is-compatible-w.patch
patch/0008-xfusion-vLLM-ascend-support-draft-model.patch
patch/0009-xfusion-vLLM-ascend-revert-llmdatadist.patch
patch/0010-xfusion-vLLM-ascend-Fix-the-issue-caused-by-bugfix-t.patch
patch/0011-xfusion-vLLM-ascend-fix-draft-model-position-oob.patch
